---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prom-read-all-pods
  namespace: prometheus
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  apiGroup: rbac.authorization.k8s.io
  namespace: prometheus
roleRef:
  kind: ClusterRole
  name: prom-monitor-pods
  apiGroup: rbac.authorization.k8s.io
