apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: lc-prod
spec:
  acme:
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: eknwipbyr51j@bk.ru
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: lc-prod
    # Enable the HTTP-01 challenge provider
    http01: {}
